---
- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    force: yes

- name: Put index.html in /var/www/html/ 
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx service
